Token fetcher re-implemented
ergolabs/ergo-dex-backend pull request #55
Opened 2022-07-07 00:15 UTC by semyonoskin

2022-07-07 14:11 UTC, GusevTimofey requested changes

2022-07-07 14:12 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/services/TokenFetcher.scala
> +        .response(asString)
Json file is:
https://github.com/ergolabs/default-token-list/blob/master/default-token-list.json

2022-07-07 14:17 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/configs/TokenFetcherConfig.scala
> +case class TokenFetcherConfig(filePath: String, rate: FiniteDuration)
It's now **url** not **filePath**

2022-07-11 07:12 UTC, GusevTimofey requested changes

2022-07-11 07:12 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/services/TokenFetcher.scala
> +        .map(_.tokens.filter(_.network == "ergo").map(tkn => TokenId.fromStringUnsafe(tkn.address)))
It is better to put "ergo" into constants

2022-07-11 07:13 UTC, GusevTimofey commented
Did you check it if it works or not?

2022-07-11 08:22 UTC, semyonoskin commented
Ye, works fine

2022-07-11 10:59 UTC, GusevTimofey approved these changes

2022-07-11 11:07 UTC, oskin1 approved these changes

2022-07-11 11:07 UTC, oskin1 commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/services/TokenFetcher.scala
> +    final case class TokenResponse(tokens: List[Token])
Please move case class declarations outside class. E.g to TokenFetcher object level.

2022-07-15 10:06 UTC, merged